import { useEffect, useRef, useState } from "react";
import { loadAIConfig, saveAIConfig } from "@/utils/ai-config";

const AITerminalView = () => {
  const [config, setConfig] = useState<any>({ provider: "deepseek", modelId: "deepseek-chat", apiKey: "", apiBaseUrl: "", systemPrompt: "你是一个简洁、准确的工程助手。" });
  const [messages, setMessages] = useState<{ role: "user" | "assistant"; content: string }[]>([]);
  const [draft, setDraft] = useState("");
  const [loading, setLoading] = useState(false);
  const [notice, setNotice] = useState("");
  const portRef = useRef<chrome.runtime.Port | null>(null);
  useEffect(() => { void loadAIConfig().then((value) => setConfig((current: any) => ({ ...current, ...value }))).catch(() => undefined); return () => portRef.current?.disconnect(); }, []);
  const send = () => { const prompt = draft.trim(); if (!prompt || loading) return; setDraft(""); setMessages((current) => [...current, { role: "user", content: prompt }, { role: "assistant", content: "" }]); setLoading(true); if (!chrome.runtime?.connect) { setMessages((current) => current.map((item, index) => index === current.length - 1 ? { ...item, content: "当前环境未连接扩展后台。" } : item)); setLoading(false); return; } const messageId = `options-${Date.now()}`; const port = chrome.runtime.connect({ name: `ai-conversation-${messageId}` }); portRef.current = port; port.onMessage.addListener((message: any) => { if (message.payload?.messageId !== messageId) return; if (message.type === "AI_CONVERSATION_STREAM_DATA") setMessages((current) => current.map((item, index) => index === current.length - 1 ? { ...item, content: item.content + (message.payload.content || "") } : item)); if (message.type === "AI_CONVERSATION_COMPLETE" || message.type === "AI_CONVERSATION_ERROR") { setLoading(false); port.disconnect(); } }); port.postMessage({ type: "START_AI_CONVERSATION", payload: { prompt, messageId, provider: config.provider, model: config.modelId, apiKey: config.apiKey, apiBaseUrl: config.apiBaseUrl, role: "bridge_aegis_terminal", systemPrompt: config.systemPrompt } }); };
  return <section className="options-view options-ai"><header className="options-view__heading"><span>AEGIS TERMINAL / DECK-07</span><h2>星舰 AI 终端</h2></header><div className="options-grid-2"><div className="options-panel"><h3>模型链路</h3><label>提供商<select value={config.provider} onChange={(e) => setConfig({ ...config, provider: e.target.value })}><option value="deepseek">DeepSeek</option><option value="openai">OpenAI Compatible</option><option value="custom">Custom Gateway</option></select></label><label>模型 ID<input value={config.modelId || ""} onChange={(e) => setConfig({ ...config, modelId: e.target.value })} /></label><label>API Base URL<input value={config.apiBaseUrl || ""} onChange={(e) => setConfig({ ...config, apiBaseUrl: e.target.value })} /></label><label>API Key<input type="password" value={config.apiKey || ""} onChange={(e) => setConfig({ ...config, apiKey: e.target.value })} /></label><label>系统 Prompt<textarea rows={8} value={config.systemPrompt || ""} onChange={(e) => setConfig({ ...config, systemPrompt: e.target.value })} /></label><button type="button" onClick={() => void saveAIConfig(config).then(() => setNotice("AI 链路已保存"))}>保存链路设置</button></div><div className="options-panel options-chat"><div className="options-chat__log">{messages.length === 0 ? <p className="options-empty">AI 终端已待命，输入问题开始对话。</p> : messages.map((message, index) => <article className={`options-chat__message options-chat__message--${message.role}`} key={index}><strong>{message.role === "user" ? "USR" : "AEGIS"}</strong><p>{message.content || "..."}</p></article>)}</div><div className="options-inline"><textarea value={draft} rows={3} placeholder="输入指令，Enter 发送" onChange={(e) => setDraft(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); } }} /><button type="button" disabled={loading} onClick={send}>{loading ? "传输中" : "发送"}</button></div></div></div><div className="options-view__notice">{notice}</div></section>;
};
export default AITerminalView;
